// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package sdj3.assignment3_1.protobuf;

public interface RequestTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input_text = 1;</code>
   * @return The inputText.
   */
  java.lang.String getInputText();
  /**
   * <code>string input_text = 1;</code>
   * @return The bytes for inputText.
   */
  com.google.protobuf.ByteString
      getInputTextBytes();
}
